[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "npm run build"
  publish = "build"

# Specify base directory explicitly
[build.environment]
  NODE_VERSION = "14"
  NPM_VERSION = "7"